### ISSUE TITLE
Lacoro public db not visible

### ISSUE THREAD

**Issue by lodha13** [LaCoro/ConsumerFlutterApp#76]
Hi

I was going through the readme documentation and found that lacoro publoc db is not accessible in our country ca you please export file of that. I am really interested in building my own ecom app.

Will be really grateful to you

**Comment by llanox** [comment]
It's weird. Let me check.

**Comment by lodha13** [comment]
Even the app in google play store in not available

**Comment by llanox** [comment]
Please, create an account in Back4App and send me the email that you used
to create it so I can transfer to that account a clone of the DB. It seems
that publishing a public DB is not available anymore.

>

**Comment by lodha13** [comment]
abhisheklodha13@gmail.com

Also can I clone and make my own e-com without any liability or license issue?

**Comment by llanox** [comment]
Sure, no problem. It's under the MIT License that is a very permissive license. 
I just transferred a clone of the Back4app App to your account so you can use it as an example to create your own e-commerce.

Let us know if you publish something based on it.

Thanks.
